name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@3.3
      with:
        cli: 1.10.3.849

    - name: Run Tests
      run: clojure -X:test
